# Generated by Django 5.0.3 on 2024-03-26 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0001_initial'),
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='problems',
            field=models.ManyToManyField(to='challenges.problems'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
