# Generated by Django 5.0.3 on 2025-02-18 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationcode',
            name='user',
        ),
        migrations.DeleteModel(
            name='ResetCode',
        ),
        migrations.DeleteModel(
            name='VerificationCode',
        ),
    ]
