# Generated by Django 5.0.3 on 2024-04-02 00:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
        ('challenges', '0004_alter_problemquiz_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_complete', models.BooleanField(default=False)),
                ('current_question', models.IntegerField(default=0)),
                ('problem_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.problemitem')),
                ('problem_quiz', models.ManyToManyField(to='challenges.problemquiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
