# Generated by Django 5.0.3 on 2024-04-02 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_userquiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquiz',
            name='problem_item',
        ),
    ]
