# Generated by Django 5.0.3 on 2024-04-02 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_userquiz_problem_item'),
        ('challenges', '0004_alter_problemquiz_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuestionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_question', models.IntegerField(default=1)),
                ('is_complete', models.BooleanField(default=False)),
                ('answers', models.ManyToManyField(to='challenges.useranswer')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.problemitem')),
            ],
        ),
    ]
