# Generated by Django 5.0.3 on 2024-04-03 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_userquestionattempt_user'),
        ('challenges', '0005_useranswer_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquiz',
            name='problem_quiz',
        ),
        migrations.AddField(
            model_name='userquiz',
            name='problem_quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='challenges.problemquiz'),
        ),
    ]
