# Generated by Django 5.0.3 on 2024-04-03 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_remove_userquiz_problem_quiz_userquiz_problem_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquiz',
            name='total_score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
