# Generated by Django 5.0.3 on 2024-04-03 03:04

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_userquiz_is_noted'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquiz',
            name='image_code',
            field=models.ImageField(blank=True, null=True, upload_to=authentication.models.UserQuiz.user_directory_path),
        ),
    ]
