# Generated by Django 5.0.3 on 2024-04-03 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_userquiz_image_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquiz',
            name='is_full',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
