# Generated by Django 5.0.3 on 2024-04-05 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_userquiz_is_full'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('score', 'username')},
        ),
    ]
