# Generated by Django 5.0.3 on 2024-04-05 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-score', 'username')},
        ),
    ]
