# Generated by Django 5.0.3 on 2025-02-18 22:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='fa-code', help_text='Font Awesome icon class', max_length=50)),
                ('order', models.IntegerField(default=0, help_text='Order in which category appears')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='attachment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attachment',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description of the attachment'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='file_type',
            field=models.CharField(default=django.utils.timezone.now, help_text="Type of file (e.g., 'dataset', 'template', 'test_case')", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='challenge',
            name='estimated_time',
            field=models.IntegerField(default=30, help_text='Estimated time in minutes to complete'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, help_text='Challenges that should be completed before this one', to='challenges.challenge'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenges', to='challenges.category'),
        ),
    ]
