# Generated by Django 5.0.3 on 2025-02-16 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemsolution',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solution',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
