# Generated by Django 5.0.3 on 2024-03-29 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_alter_problemitem_attachments_problemitemsubmission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problems',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
