# Generated by Django 5.0.3 on 2024-04-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0006_ratings_parent_alter_ratings_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
