# Generated by Django 5.0.3 on 2024-04-05 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0008_ratings_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratings',
            options={'ordering': ('-created_at',)},
        ),
    ]
