# Generated by Django 5.0.3 on 2024-04-12 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0009_alter_ratings_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemitem',
            name='title',
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='problems',
            name='title',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
