# Generated by Django 5.0.3 on 2024-04-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0010_alter_problemitem_title_alter_problems_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problemitem',
            options={'ordering': ('points',)},
        ),
        migrations.AlterField(
            model_name='attachment',
            name='title',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='problemitem',
            name='title',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='problemquiz',
            name='title',
            field=models.TextField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='problems',
            name='title',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='title',
            field=models.TextField(unique=True),
        ),
    ]
