# Generated by Django 5.0.3 on 2024-04-12 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0011_alter_problemitem_options_alter_attachment_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemitem',
            name='slug',
            field=models.SlugField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='problemquiz',
            name='slug',
            field=models.SlugField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='problems',
            name='slug',
            field=models.SlugField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='slug',
            field=models.SlugField(blank=True, max_length=1500, null=True),
        ),
    ]
