# Generated by Django 5.0.3 on 2024-04-13 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0012_alter_problemitem_slug_alter_problemquiz_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problemitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='challenges-image/'),
        ),
    ]
