# Generated by Django 5.0.3 on 2024-04-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0016_problemsolution_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problemsolution',
            options={'ordering': ('-pk',)},
        ),
        migrations.AlterUniqueTogether(
            name='problemsolution',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='problemsolution',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
