# Generated by Django 5.0.3 on 2024-04-20 16:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0017_alter_problemsolution_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='problemsolution',
            unique_together={('user', 'problem_item')},
        ),
    ]
