# Generated by Django 5.0.3 on 2024-09-16 12:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0019_comments_parent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problemitem',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterUniqueTogether(
            name='problemsolution',
            unique_together={('user', 'problem_item', 'language')},
        ),
    ]
